optimizer: {
  type: AdamW,
  kwargs: {
    lr: 0.0005,
    #lr: 0.0001,
    #lr: 0.001,
    weight_decay: 0.05
  } }

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 300,
    initial_epochs: 10
  } }

dataset: {
  train: { _base_: cfgs/dataset_configs/ScanObjectNN_hardest.yaml,
           others: { subset: 'train' } },
  val: { _base_: cfgs/dataset_configs/ScanObjectNN_hardest.yaml,
         others: { subset: 'test' } },
  test: { _base_: cfgs/dataset_configs/ScanObjectNN_hardest.yaml,
          others: { subset: 'test' } } }
model: {
  NAME: PointMamba,
  trans_dim: 384,
  depth: 12,
  cls_dim: 15,
  num_heads: 6,
  group_size: 32,
  num_group: 128,
  encoder_dims: 384,
  rms_norm: False,
  drop_path: 0.1,
  drop_out: 0.,
  method: MAMBA,
  reverse: True,
  knn_graph: 20,
  k_top_eigenvectors: 4,
  smallest: True,
  level: 4, 
  steps: 4, 
  sign: [[1,1,1,1], [1,-1,1,1], [-1,1,1,1], [-1,-1,1,1]],
  affine_geometric : False,
  alpha : 10., 
  all_distance : False,
  symmetric : True,
  self_loop : False
}


npoints: 2048
total_bs: 32
step_per_update: 1
max_epoch: 300
grad_norm_clip: 10
rotation_aug : True
scale_trans_aug : False
rotation_scale_aug : False 
rotation_all_axes_aug : False 
